---
# tasks file for ultratendency_mariadb

- name: install MariaDB server
  yum: name=mariadb-server state=present


- name: start and enable MariaDB
  service: name=mariadb state=started enabled=true


#Will help us to reproduce the "mysql_secure_installation" tasks
- name: install mysql-python
  yum: name=MySQL-python state=present

# Set the root password
- name: update mariadb root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: True
